#!/usr/bin/env python3
"""Cross-check our takeuforward-derived dataset against codolio's independent copy of the sheet.

Titles are useless for this: takeuforward renamed most problems when it redesigned the sheet
("Armstrong Numbers" -> "Check if the Number is Armstrong"), and codolio still mirrors the old
names.  Stable identifiers are the meaningful comparison, so we match on LeetCode slugs and on
takeuforward item slugs, and treat the title table as background noise.

Writes data/raw/crosscheck.md; exits non-zero when identifier agreement collapses.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw"
LC_SLUG_RE = re.compile(r"/problems/([a-z0-9-]+)")

LC_HOST_RE = re.compile(r"leetcode\.com/(?:problems/|accounts/login/\?next=/problems/)([a-z0-9-]+)")


def lc_slug(url: str | None) -> str | None:
    """LeetCode slug from a problem URL, including the sheet's login-wall form.

    The sheet links "Celebrity Problem" at /accounts/login/?next=/problems/find-the-celebrity/,
    so a plain /problems/ match is not enough on its own, and matching /problems/ without requiring
    the leetcode.com host would also swallow takeuforward's /plus/dsa/problems/<slug> URLs.
    """
    if not url or "leetcode.com" not in url:
        return None
    match = LC_SLUG_RE.search(url)
    return match.group(1) if match else None



def norm(text: str) -> str:
    text = (text or "").lower()
    text = re.sub(r"\(.*?\)", " ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    stop = {"the", "a", "an", "of", "in", "on", "to", "and", "for", "with", "problem"}
    return " ".join(w for w in text.split() if w not in stop)


def main() -> int:
    base = json.loads((RAW / "base_items.json").read_text())
    codolio = json.loads((RAW / "codolio.json").read_text())
    ours = [i for i in base if i["layout"] == "practice"]

    our_lc = {slug: i for i in ours if (slug := lc_slug(i.get("leetcodeUrl")))}
    cod_lc = {slug: r for r in codolio if (slug := lc_slug(r.get("problemUrl")))}
    our_tuf = {i["slug"]: i for i in ours}
    cod_tuf = {r["problemId"]: r for r in codolio if r.get("platformRaw") == "tuf"}

    lc_common = sorted(set(our_lc) & set(cod_lc))
    lc_ours_only = sorted(set(our_lc) - set(cod_lc))
    lc_theirs_only = sorted(set(cod_lc) - set(our_lc))
    tuf_common = sorted(set(our_tuf) & set(cod_tuf))

    coverage = len(lc_common) / len(our_lc) if our_lc else 0.0

    titles_ours = {norm(i["title"]) for i in ours}
    titles_theirs = {norm(r["title"]) for r in codolio}

    lines = [
        "# Dataset cross-check: takeuforward sheet payload vs codolio",
        "",
        f"Generated by `scripts/crosscheck.py`. Codolio row count: {len(codolio)}; "
        f"our practice problems: {len(ours)}.",
        "",
        "## LeetCode slugs (stable identifier)",
        "",
        f"- ours: **{len(our_lc)}** unique slugs",
        f"- codolio: **{len(cod_lc)}** unique slugs",
        f"- shared: **{len(lc_common)}**",
        f"- of our LeetCode-linked problems, **{coverage:.1%}** appear in codolio",
        "",
        f"### In our sheet but not in codolio ({len(lc_ours_only)})",
        "",
        "Codolio usually records the takeuforward link for these rows, so an entry here is not"
        " necessarily an error; `coin-change-2` / `implement-strstr` were stale slugs that"
        " `scripts/fetch_lc_extra.py` resolved to `coin-change-ii` /"
        " `find-the-index-of-the-first-occurrence-in-a-string`.",
        "",
        *[f"- `{s}` - {our_lc[s]['title']}" for s in lc_ours_only],
        "",
        f"### In codolio but not in our sheet ({len(lc_theirs_only)})",
        "",
        *[f"- `{s}` - {cod_lc[s]['title']}".replace("\\\\", "") for s in lc_theirs_only],
        "",
        "## takeuforward item slugs",
        "",
        f"- ours: {len(our_tuf)}, codolio (rows it marks `tuf`): {len(cod_tuf)}, shared: {len(tuf_common)}",
        "",
        "## Normalized-title overlap (weak signal, kept for the record)",
        "",
        f"- identical normalized titles: {len(titles_ours & titles_theirs)}",
        f"- our titles only: {len(titles_ours - titles_theirs)} "
        "(mostly takeuforward's 2024+ renames, e.g. \"Armstrong Numbers\" -> "
        "\"Check if the Number is Armstrong\")",
        f"- codolio titles only: {len(titles_theirs - titles_ours)} "
        "(includes the concept-only lessons we do not ship)",
        "",
    ]
    (RAW / "crosscheck.md").write_text("\n".join(lines))
    print(
        f"lc slugs: ours {len(our_lc)} codolio {len(cod_lc)} shared {len(lc_common)} "
        f"({coverage:.1%} of ours), ours-only {len(lc_ours_only)}, codolio-only {len(lc_theirs_only)}"
    )
    print(f"tuf slugs shared: {len(tuf_common)} (ours {len(our_tuf)}, codolio {len(cod_tuf)})")
    print(f"identical normalized titles: {len(titles_ours & titles_theirs)}")
    if coverage < 0.9:
        print("FAIL: under 90% of our LeetCode links are confirmed by the second source")
        return 1
    print("ok: identifier agreement is high")
    return 0


if __name__ == "__main__":
    sys.exit(main())
